version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: poker_postgres
    environment:
      POSTGRES_USER: poker_user
      POSTGRES_PASSWORD: poker_password
      POSTGRES_DB: poker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poker_user -d poker_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: poker_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: poker_db
      DATABASE_USER: poker_user
      DATABASE_PASSWORD: poker_password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: poker_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: